{% set name = "lume-astra" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9a521340635a880812c724424dcf01b14efb3aff81e5ac13bffd5463f5a1ac0d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - distgen
    - numpy
    - openpmd-beamphysics

test:
  imports:
    - astra

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python wrapper for Astra (A Space Charge Tracking Algorithm, DESY) for use in LUME
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
